method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  batch_size:
    values: [1, 32, 64, 128]
program: cs336_basics/transformer/trainer.py
command:
  - python3
  - ${program}
  - --config
  - cs336_basics/transformer/config/default.yaml
  - --total_steps
  - 5000
  - --warmup_steps
  - 500
  - --annealing_steps
  - 5000
  - --experiment_name
  - sweep_batch_size
  - --training_minutes
  - 30
